## NUMPY ARRAYS AND MATRICES

In [3]:
# importing required modules
import numpy as np

In [19]:
# create ndarrays from lists
# note: every element must be the same type (will be converted if possible)
data1 = [1, 2, 3, 4, 5]   # defining a list
print (data1, len(data1), type(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), type(arr1))

data2 = [range(1, 5), range(5, 9)]   # defining list of lists
print (data2, len(data2), type(data2))
arr2 = np.array(data2)
print (arr2, len(arr2), type(arr2))

[1, 2, 3, 4, 5] 5 <class 'list'>
[1 2 3 4 5] 5 <class 'numpy.ndarray'>
[range(1, 5), range(5, 9)] 2 <class 'list'>
[[1 2 3 4]
 [5 6 7 8]] 2 <class 'numpy.ndarray'>


In [22]:
# examining arrays
print (arr1.dtype, arr2.dtype)
print (arr1.ndim, arr2.ndim)
print (arr1.shape, arr2.shape)    # (5,) => Singleton notation of a tuple
print (arr1.size, arr2.size)
print (len(arr1), len(arr2))

int32 int32
1 2
(5,) (2, 4)
5 8
5 2


In [30]:
# create special arrays
print (np.zeros(10))
print (np.zeros(10).astype(int))
print (np.zeros(10).astype(str))
print (np.ones(10))
print (np.ones(10).astype(int))
print (np.ones(10).astype(str))
np.zeros(10)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]
['0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0']
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1 1 1 1]
['1.0' '1.0' '1.0' '1.0' '1.0' '1.0' '1.0' '1.0' '1.0' '1.0']


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
print (np.linspace(0, 1, 5))
print (np.logspace(0, 3, 4))

[0.   0.25 0.5  0.75 1.  ]
[   1.   10.  100. 1000.]


In [40]:
float_array = np.arange(5).astype(float)
print (float_array)
float_array = np.arange(2, 10, 1).astype(float)
print (float_array)
float_array = np.arange(2, 10, 3).astype(float)
print (float_array)
int_array = np.arange(15)
print (int_array)
int_array = np.arange(15).reshape(3, 5)
print (int_array)

[0. 1. 2. 3. 4.]
[2. 3. 4. 5. 6. 7. 8. 9.]
[2. 5. 8.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [46]:
float_array = np.arange(15).astype(float)
print (float_array)
float_array = np.arange(15).astype(float).reshape(3, 5)
print (float_array)
float_array = np.arange(15).reshape(3, 5).astype(float)
print (float_array)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]]
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]]


In [54]:
# indexing and slicing
print (arr1)
print (arr1[0], arr1[1], arr1[2], arr1[3], arr1[4])
print (arr1[-5], arr1[-4], arr1[-3], arr1[-2], arr1[-1])
print (arr1[1:], arr1[:3])
print (arr1[::2])

[1 2 3 4 5]
1 2 3 4 5
1 2 3 4 5
[2 3 4 5] [1 2 3]
[1 3 5]


In [70]:
print (arr2)
print (arr2[0,2], arr2[0][2], arr2[-2, -2], arr2[-2][-2], arr2[0,-2], arr2[-2, 2])
print (arr2[:, 1:3])
print (arr2[0:2, 1:3])

[[1 2 3 4]
 [5 6 7 8]]
3 3 3 3 3 3
[[2 3]
 [6 7]]
[[2 3]
 [6 7]]


In [71]:
print(arr2[:, 1:4])

[[2 3 4]
 [6 7 8]]


In [72]:
print(arr2[:,1:])

[[2 3 4]
 [6 7 8]]


In [79]:
# Views and copies
arr = np.arange(10)
print (arr)
print (arr[5:8])
arr[5:8] = 12
print (arr)
arr_view = arr[1:3]
print (arr_view)
arr_view[:] = 100
print (arr, arr_view)

[0 1 2 3 4 5 6 7 8 9]
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]
[1 2]
[  0 100 100   3   4  12  12  12   8   9] [100 100]


In [82]:
arr_copy = arr[5:8].copy()
print (arr, arr_copy)
arr_copy[:] = 500
print (arr, arr_copy)

[  0 100 100   3   4  12  12  12   8   9] [12 12 12]
[  0 100 100   3   4  12  12  12   8   9] [500 500 500]


In [86]:
# using boolean arrays
arr = np.arange(15)
print (arr, arr.size)
print (arr > 5)   # generating a boolean aray
print (arr[arr > 5])   # using this boolean array as array index

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] 15
[False False False False False False  True  True  True  True  True  True
  True  True  True]
[ 6  7  8  9 10 11 12 13 14]


In [91]:
bool_arr = (arr > 3) & (arr < 10)
print (bool_arr)
print (arr[bool_arr])
bool_arr = (arr % 2 == 0)
print (bool_arr)
print (arr[bool_arr])

[False False False False  True  True  True  True  True  True False False
 False False False]
[4 5 6 7 8 9]
[ True False  True False  True False  True False  True False  True False
  True False  True]
[ 0  2  4  6  8 10 12 14]


In [100]:
names = np.array(['Bob','Joe','Will','Bob'])
print (names, len(names))
print (names != 'Bob')
print (names[names != 'Bob'])
print ((names == 'Bob') | (names == 'Will'))
print (names[(names == 'Bob') | (names == 'Will')])
print (names[names != 'Bob'])
names[names != 'Bob'] = 'Tom'
print (names)
print (np.unique(names))

['Bob' 'Joe' 'Will' 'Bob'] 4
[False  True  True False]
['Joe' 'Will']
[ True False  True  True]
['Bob' 'Will' 'Bob']
['Joe' 'Will']
['Bob' 'Tom' 'Tom' 'Bob']
['Bob' 'Tom']


In [113]:
# vectorized operations
nums = np.arange(5)
print (nums, len(nums))
times = 5
print (nums * times, times * nums)
print (np.sqrt(nums))
print (np.ceil(np.sqrt(nums)), np.isnan(nums))
print (nums, np.arange(5), nums + np.arange(5))
print (np.maximum(nums, np.array([1, -2, 3, -4, 5])))

[0 1 2 3 4] 5
[ 0  5 10 15 20] [ 0  5 10 15 20]
[0.         1.         1.41421356 1.73205081 2.        ]
[0. 1. 2. 2. 2.] [False False False False False]
[0 1 2 3 4] [0 1 2 3 4] [0 2 4 6 8]
[1 1 3 3 5]


In [120]:
# compute Euclidian Distance between two vectors
vect1 = np.random.randn(10)  # randn method generates normalized random numbers, random numbers with average ~= 0 and std dev. ~= 1
vect2 = np.random.randn(10)
print (vect1, len(vect1))
print (vect2, len(vect2))
print (np.average(vect1), np.std(vect1), np.average(vect2), np.std(vect2))

[-1.49941486  0.16973202 -1.02934754 -1.64902456 -0.93781275 -1.41601749
  0.02054103 -1.4194223  -1.06188746  1.33459485] 10
[ 1.08932923  2.27181516 -1.00638975 -0.58405743  0.55678612 -0.36740643
  0.13840903 -1.16619673  0.2661554   0.14527968] 10
-0.7488059068903526 0.9086978426510529 0.13437242919662218 0.9714567022650903


In [122]:
vectt1 = np.random.randn(50000)  
vectt2 = np.random.randn(50000)
print (np.average(vectt1), np.std(vectt1), np.average(vectt2), np.std(vectt2))

0.0034764618037137454 1.001746334744338 0.0026263436400069786 1.0009424244304501


In [131]:
print (vect1, len(vect1))
print (vect2, len(vect2))
dist = np.sqrt(np.sum((vect1 - vect2) ** 2))
print (dist)
total = 0
for i in range(len(vect1)):
    total = total + (vect1[i] - vect2[i]) ** 2
total = np.sqrt(total)
print (total)

[-1.49941486  0.16973202 -1.02934754 -1.64902456 -0.93781275 -1.41601749
  0.02054103 -1.4194223  -1.06188746  1.33459485] 10
[ 1.08932923  2.27181516 -1.00638975 -0.58405743  0.55678612 -0.36740643
  0.13840903 -1.16619673  0.2661554   0.14527968] 10
4.341039854525622
4.341039854525622


In [141]:
# maths and stats
rnd = np.random.randn(4, 2)   # random normals in 4x2 array
print (rnd, len(rnd))
print (rnd.mean(), np.average(rnd), rnd.std(), rnd.std() ** 2, rnd.var(), rnd.sum())
print (rnd.argmin(), rnd.argmax())
print (rnd.sum(axis = 0), rnd.sum(axis = 1))

[[-1.2867898  -0.76872884]
 [ 0.29082651 -1.60447635]
 [ 1.75268065  0.59767862]
 [-0.65162205  1.16633004]] 4
-0.0630126537131146 -0.0630126537131146 1.1229413341750074 1.2609972399987457 1.2609972399987455 -0.5041012297049168
3 4
[ 0.1050953  -0.60919653] [-2.05551864 -1.31364984  2.35035926  0.51470799]


In [147]:
# method for boolean arrays
print (rnd > 0)
print ((rnd > 0).sum(), (rnd > 0).any(), (rnd > 0).all())

[[False False]
 [ True False]
 [ True  True]
 [False  True]]
4 True False


In [155]:
# reshape, transpose, flatten
nums = np.arange(32).reshape(8, 4)
print (nums)
nums = nums.T   # transpose
print (nums)
nums = nums.T   # transpose
print (nums)
nums = nums.flatten()
print (nums)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[ 0  4  8 12 16 20 24 28]
 [ 1  5  9 13 17 21 25 29]
 [ 2  6 10 14 18 22 26 30]
 [ 3  7 11 15 19 23 27 31]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]


In [167]:
# random numbers generated with a seed value
np.random.seed(1234)
print (np.random.rand(2, 3))
print (np.random.randn(10))
print (np.random.randint(0, 2, 30))

[[0.19151945 0.62210877 0.43772774]
 [0.78535858 0.77997581 0.27259261]]
[ 8.59588414e-01 -6.36523504e-01  1.56963721e-02 -2.24268495e+00
  1.15003572e+00  9.91946022e-01  9.53324128e-01 -2.02125482e+00
 -3.34077366e-01  2.11836468e-03]
[0 0 0 1 1 1 0 1 1 0 1 0 1 0 1 1 1 1 0 1 0 1 1 0 0 1 0 0 1 1]


In [172]:
print (np.random.rand(2, 3))

[[0.99208147 0.95880176 0.79196414]
 [0.28525096 0.62491671 0.4780938 ]]


### Broadcasting

<img src = "NumpyBroadcasting.png" width = 500 height = 500>

In [173]:
a = np.array([[ 0,  0,  0],
              [10, 10, 10],
              [20, 20, 20],
              [30, 30, 30]])
b = np.array([0, 1, 2])
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [174]:
a = np.array([[ 0],
              [10],
              [20],
              [30]])
b = np.array([0, 1, 2])
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])